perception_node:
  ros__parameters:
    model_filename: "bestmodel.pt"
    confidence_threshold: 0.5
    bark_distance_threshold: 3.0
    target_classes: ["apple", "banana", "pizza", "bad_apple", "bad_banana", "bad_pizza", 
                     "toilet", "nurse", "cone_red", "cone_blue", "cone_green", "box", "tile_red", "stop_sign"]
    debug_mode: true